const data = [
  {
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
  },
  {
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
    
  },
  {
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
    
  },
  {
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
    
  },
  {
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
    
  },
  {
    id: 6,
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
    
  },
  {
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
    
  },
  {
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
    
  },
  {
    id: 9,
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
   
  },
  {
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
    
  },
  {
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
    
  },
  {
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
    
  },
  {
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
    
  },
  {
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
    
  },
  {
    job_id: 'AHD4649',
    pickup_date_time: '23:00 Tue, 17 Sep, 2019',
    pickup_postcode: 'TW6 3XQ',
    drpoff_poostcode: 'W10 5NT',
    pickup_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    dropoff_address: 'LHR Terminal 4 World Duty Free, Longford, Hoston, London',
    service_type: 'Private',
    drive_fare: 'Services',
    
  },
]
export { data }
